# Documentation: https://roots.io/trellis/docs/vault/
vault_mysql_root_password: "p74wxbMQLoOjGBmZ0jUztzm1"

# Variables to accompany `group_vars/development/wordpress_sites.yml`
# Note: the site name (`example.com`) must match up with the site name in the above file.
vault_wordpress_sites:
  catheneukum.com:
    admin_password: "4FWPK12gBhYc89ZcjzUX3BbK"
    env:
      db_password: "eMeHxupw0Ah1rAw7thohEFpw"
